spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/crm}
    username: ${SPRING_DATASOURCE_USERNAME:crm}
    password: ${SPRING_DATASOURCE_PASSWORD:crm}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  thymeleaf:
    cache: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
